x-customizable-image: &customizable_image
  image: frappe/erpnext:v14.38.0
  pull_policy: always
  restart: unless-stopped

x-backend-defaults: &backend_defaults
  <<: *customizable_image
  volumes:
    - sites:/home/frappe/frappe-bench/sites
    # Mount your custom app path here, use forward slashes
    - /c/Projects/Marketplace/freelancer-marketplace/backend/freelancer_marketplace:/home/frappe/frappe-bench/apps/freelancer_marketplace

services:
  pgdb:
    image: postgres:13
    environment:
      POSTGRES_DB: frappe
      POSTGRES_USER: frappe
      POSTGRES_PASSWORD: frappe
    volumes:
      - pgdb-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis-cache:
    image: redis:alpine
    restart: unless-stopped

  redis-queue:
    image: redis:alpine
    restart: unless-stopped

  backend:
    <<: *backend_defaults
    platform: linux/amd64
    depends_on:
      - configurator
      - pgdb
      - redis-cache
      - redis-queue
    environment:
      DB_HOST: pgdb
      DB_PORT: 5432
      DB_TYPE: postgres
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379

  configurator:
    <<: *backend_defaults
    platform: linux/amd64
    ports:
      - "8000:8000" 
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $${DB_HOST};
        bench set-config -gp db_port $${DB_PORT};
        bench set-config -g db_type $${DB_TYPE};
        bench set-config -g redis_cache "redis://$${REDIS_CACHE}";
        bench set-config -g redis_queue "redis://$${REDIS_QUEUE}";
        bench set-config -g redis_socketio "redis://$${REDIS_QUEUE}";
        bench set-config -gp socketio_port $${SOCKETIO_PORT};
    environment:
      DB_HOST: pgdb
      DB_PORT: 5432
      DB_TYPE: postgres
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: 9000

  frontend:
    <<: *customizable_image
    platform: linux/amd64
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: $${host}
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: off
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend
      - websocket

  websocket:
    <<: *customizable_image
    platform: linux/amd64
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - configurator

  queue-short:
    <<: *backend_defaults
    platform: linux/amd64
    command: bench worker --queue short,default

  queue-long:
    <<: *backend_defaults
    platform: linux/amd64
    command: bench worker --queue long,default,short

  scheduler:
    <<: *backend_defaults
    platform: linux/amd64
    command: bench schedule

volumes:
  sites:
  pgdb-data:
